server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://wnt-dev.cvdjpehidk1x.us-east-1.rds.amazonaws.com:3306/wnt?useServerPrepStmts=false&rewriteBatchedStatements=true
    username: wnt
    password: zXN}k9Kd>>
    driver-class-name: com.mysql.cj.jdbc.Driver
  datasource-ocr:
    url: jdbc:mysql://wnt-dev.cvdjpehidk1x.us-east-1.rds.amazonaws.com:3306/wnt_ocr?useServerPrepStmts=false&rewriteBatchedStatements=true
    username: wnt
    password: zXN}k9Kd>>
    driver-class-name: com.mysql.cj.jdbc.Driver

  profiles:
    active: dev

aws:
  lead-document:
    name: lead-document-dev
    region: us-east-2
  assignment-term:
    region: us-east-1
    name: job-termo-cessao
  titles-ocr:
    region: us-east-2
    name: wnt-titles-ocr-dev
  committees:
    region: us-east-2
    name: wnt-committees-dev
  juridical:
    region: us-east-2
    name: wnt-juridical-dev
  compliance-evento:
    region: us-east-2
    name: compliance-evento-dev
  compliance-treinamento:
    region: us-east-2
    name: compliance-treinamento-dev
  discharge-certificate:
    region: us-east-2
    name: wnt-termos-quitacao-templates-develop
  assignor-documents:
    region: us-east-2
    name: wnt-capital-assignor-documents-dev
  pdffiles:
    region: us-east-2
    name: wnt-ccbpdf-files-develop
  relatorios:
    region: us-east-1
    name: wntccbrelatorios
  public:
    region: us-east-2
    name: wnt-public-develop
  nfs:
    region: us-east-2
    name: wnt-public-nfs-develop
  lamina:
    baseS3Url: https://wnt-public-lamina-develop.s3.us-east-2.amazonaws.com/
    region: us-east-2
    name: wnt-public-lamina-develop
    template:
      region: us-east-2
      name: wnt-lamina-template-develop
  bucket:
    client:
      region: us-east-2
      name: wnt-clients-develop
    temp:
      region: us-east-2
      name: wnt-temp-files-dev
    region: us-east-2
    name: wnt-ftp-files-develop
  prospection:
    name: wnt-prospection-templates-develop
    region: us-east-2
  public-site-api:
    name: wnt-public-site-api-develop
    region: us-east-2
  public-site-api2:
    name: wnt-public-site-api2-develop
    region: us-east-2
  audiofiles:
    name: wnt-ccbaudio-files-develop
    region: us-east-2
  tedfiles:
    name: wnt-tedpdf-files-prd
    region: us-west-1
  billing:
    region: us-east-1
    name: wnt-billing-cnab-prd
  sqs:
    region: us-east-2
    name: wnt-ftp-files-dev
    url: https://sqs.us-east-2.amazonaws.com/523638500337/wnt-ftp-files-dev
    aux:
      region: us-east-2
      name: wnt-ftp-aux-dev
      url: https://sqs.us-east-2.amazonaws.com/523638500337/wnt-ftp-aux-dev
    estoque:
      region: us-east-2
      name: wnt-estoque-files-dev
      url: https://sqs.us-east-2.amazonaws.com/523638500337/wnt-estoque-files-dev
    download:
      region: us-east-2
      name: wnt-download-files-env-dev
      url: https://sqs.us-east-2.amazonaws.com/523638500337/wnt-download-files-env-dev
    titles:
      region: us-east-2
      name: wnt-title-files
      url: https://sqs.us-east-2.amazonaws.com/523638500337/wnt-title-files
    client:
      region: us-east-2
      name: wnt-clients-develop
      url: https://sqs.us-east-2.amazonaws.com/523638500337/wnt-clients-develop
    reprocess:
      region: us-east-2
      name: wnt-reprocess-develop
      url: https://sqs.us-east-2.amazonaws.com/523638500337/wnt-reprocess-develop
    prospection:
      region: us-east-2
      name: wnt-prospection-templates-develop
      url: https://sqs.us-east-2.amazonaws.com/523638500337/wnt-prospection-templates-develop
    robot:
      region: us-east-2
      name: wnt-robot-dev
      url: https://sqs.us-east-2.amazonaws.com/523638500337/wnt-robot-dev
    stock:
      region: us-east-2
      name: wnt-stock-dev
      url: https://sqs.us-east-2.amazonaws.com/523638500337/wnt-stock-dev
    validate-remittance:
      region: us-east-2
      name: wnt-validate-remittance-dev
      url: https://sqs.us-east-2.amazonaws.com/523638500337/wnt-validate-remittance-dev

omie:
  appKey: 1763300903364
  appSecret: 0ca17889a4a55e566c7f05f159d1d32b

singulareApi:
  base-url: https://api-portal.singulare.com.br/v2
  market-base-url: /report/netreport/market/
  fund-base-url: https://api-portal.singulare.com.br/v2/netreport/report/fund/
  extracts-base-url: /conta-corrente/bank-account/statement/
  quotaholders-base-url: /shareholder/rel-posicao-cotista/
  singulare-id: TKoFZl0_BVghP7LtykhXwJikzAhgPwsbMmg
  singulare-secret: wL-huAkSOELk_ZsdUv2e1IQrMWI37po5RLD2uZL8xMZBU_kkMW_kys0COb95vzzRpiIkD-UKafu6z_1N18IMwPQiWeKyfpUPWzyoD_ozGX5KXbu3sJzpMmi4BhLxGdWmbbTqxPsEbAfCZGDh_p8cqeGX0QXjwD1FfrSruXFi8yxgdeK0BA6DUswQMVRsNS2uSuYi9OXi_popuUfHhWkrq2GcW9LSZL3aDtCI9tPpr9-YIMYjASHu7Ev94g
  job:
    name: singulareApiJob
    triggerName: singulareApiTrigger
    minToRun: 30
  extracts:
    job:
      name: singulareApiExtractsJob
      triggerName: singulareApiExtractsTrigger
      minToRun: 45

clickSign:
  url: https://sandbox.clicksign.com
  accessToken: a2171bc0-c39e-4f2f-ac02-cb033cb59583
